server:
  port: 8080
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://localhost/example?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 1800000
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null

mybatis:
  mapper-locations:
    - classpath:{{{packageDir}}}/domain/*Mapper.xml

logging:
  level:
    root: info
    {{{packagePath}}}.repository: debug

